name: Add to Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue or bug to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/okjodom/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: issue, bug
          label-operator: OR
